build: fix typo in tools.go
builds have been failing with this error

    Error: tools.go:6:2: expected 'STRING', found '-'

turns out the go imports statement supports underscores _
as module aliases but not hyphens -